-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "passwordHash" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chats" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "title" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "chats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_messages" (
    "id" TEXT NOT NULL,
    "chatId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "toolCallId" TEXT,
    "toolResult" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "records" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "rawText" TEXT NOT NULL,
    "contentHash" TEXT NOT NULL,
    "context" JSONB,
    "status" TEXT NOT NULL DEFAULT '보관됨',
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "conversation_segments" (
    "id" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "chatId" TEXT,
    "messageId" TEXT,
    "segmentIndex" INTEGER NOT NULL DEFAULT 0,
    "rawStart" INTEGER NOT NULL,
    "rawEnd" INTEGER NOT NULL,
    "rawText" TEXT NOT NULL,
    "contextBefore" TEXT,
    "contextAfter" TEXT,
    "skillName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "conversation_segments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "wiki_nodes" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "topics" TEXT[],
    "tags" TEXT[],
    "categories" TEXT[],
    "hiddenTags" TEXT[],
    "hiddenCategories" TEXT[],
    "status" TEXT NOT NULL DEFAULT '활성',
    "classificationState" TEXT,
    "classificationCandidates" TEXT,
    "latestVersion" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "wiki_nodes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "node_versions" (
    "id" TEXT NOT NULL,
    "nodeId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "summary" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "topics" TEXT[],
    "tags" TEXT[],
    "categories" TEXT[],
    "changedBy" TEXT NOT NULL DEFAULT 'user',
    "changeType" TEXT,
    "changeNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "node_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proposals" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "targetNodeId" TEXT,
    "sourceNodeId" TEXT,
    "action" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "proposalHash" TEXT NOT NULL,
    "evidenceSegmentIds" TEXT[],
    "relatedSegmentIds" TEXT[],
    "relatedRecordId" TEXT,
    "baseNodeVersion" INTEGER,
    "skillHash" TEXT,
    "hasSensitiveInfo" BOOLEAN NOT NULL DEFAULT false,
    "sensitiveInfoWarning" TEXT,
    "sensitiveInfoNodeIds" TEXT[],
    "status" TEXT NOT NULL DEFAULT '제안됨',
    "decisionAt" TIMESTAMP(3),
    "decisionAction" TEXT,
    "idempotencyKey" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "proposals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proposal_evidence" (
    "id" TEXT NOT NULL,
    "proposalId" TEXT NOT NULL,
    "segmentId" TEXT NOT NULL,
    "quote" TEXT NOT NULL,
    "originalStart" INTEGER NOT NULL,
    "originalEnd" INTEGER NOT NULL,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "proposal_evidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "node_relationships" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "sourceNodeId" TEXT NOT NULL,
    "targetNodeId" TEXT NOT NULL,
    "relationType" TEXT NOT NULL,
    "description" TEXT,
    "evidence" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "proposedBy" TEXT,
    "status" TEXT NOT NULL DEFAULT '연결됨',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "node_relationships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "record_to_node" (
    "id" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "nodeId" TEXT NOT NULL,
    "nodeVersionId" TEXT,
    "changeDescription" TEXT NOT NULL,
    "reflectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "record_to_node_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "interest_trackings" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "interest" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT '미지정',
    "isExplicitlyMarked" BOOLEAN NOT NULL DEFAULT false,
    "explicitMarkedAt" TIMESTAMP(3),
    "explicitMarkedBy" TEXT,
    "firstDiscoveredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastDiscoveredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "interest_trackings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "interest_mentions" (
    "id" TEXT NOT NULL,
    "interestTrackingId" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "chatId" TEXT,
    "segmentId" TEXT,
    "role" TEXT NOT NULL,
    "messageCreatedAt" TIMESTAMP(3),
    "occurredAt" TIMESTAMP(3),
    "mentionedAt" TIMESTAMP(3) NOT NULL,
    "contextSnippet" TEXT,
    "isExplicitMark" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "interest_mentions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_memory_slots" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "slotKey" TEXT NOT NULL,
    "slotValue" JSONB NOT NULL,
    "source" TEXT,
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_memory_slots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "sid" VARCHAR NOT NULL,
    "sess" JSON NOT NULL,
    "expire" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("sid")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "records_userId_contentHash_key" ON "records"("userId", "contentHash");

-- CreateIndex
CREATE UNIQUE INDEX "node_versions_nodeId_version_key" ON "node_versions"("nodeId", "version");

-- CreateIndex
CREATE UNIQUE INDEX "proposals_proposalHash_key" ON "proposals"("proposalHash");

-- CreateIndex
CREATE UNIQUE INDEX "proposals_idempotencyKey_key" ON "proposals"("idempotencyKey");

-- CreateIndex
CREATE UNIQUE INDEX "node_relationships_sourceNodeId_targetNodeId_relationType_key" ON "node_relationships"("sourceNodeId", "targetNodeId", "relationType");

-- CreateIndex
CREATE UNIQUE INDEX "record_to_node_recordId_nodeId_key" ON "record_to_node"("recordId", "nodeId");

-- CreateIndex
CREATE UNIQUE INDEX "interest_trackings_userId_interest_key" ON "interest_trackings"("userId", "interest");

-- CreateIndex
CREATE UNIQUE INDEX "user_memory_slots_userId_slotKey_key" ON "user_memory_slots"("userId", "slotKey");

-- CreateIndex
CREATE INDEX "IDX_session_expire" ON "session"("expire");

-- AddForeignKey
ALTER TABLE "chats" ADD CONSTRAINT "chats_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_chatId_fkey" FOREIGN KEY ("chatId") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "records" ADD CONSTRAINT "records_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "conversation_segments" ADD CONSTRAINT "conversation_segments_chatId_fkey" FOREIGN KEY ("chatId") REFERENCES "chats"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "conversation_segments" ADD CONSTRAINT "conversation_segments_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "conversation_segments" ADD CONSTRAINT "conversation_segments_recordId_fkey" FOREIGN KEY ("recordId") REFERENCES "records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wiki_nodes" ADD CONSTRAINT "wiki_nodes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "node_versions" ADD CONSTRAINT "node_versions_nodeId_fkey" FOREIGN KEY ("nodeId") REFERENCES "wiki_nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_relatedRecordId_fkey" FOREIGN KEY ("relatedRecordId") REFERENCES "records"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_sourceNodeId_fkey" FOREIGN KEY ("sourceNodeId") REFERENCES "wiki_nodes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_targetNodeId_fkey" FOREIGN KEY ("targetNodeId") REFERENCES "wiki_nodes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "proposals" ADD CONSTRAINT "proposals_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "proposal_evidence" ADD CONSTRAINT "proposal_evidence_proposalId_fkey" FOREIGN KEY ("proposalId") REFERENCES "proposals"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "proposal_evidence" ADD CONSTRAINT "proposal_evidence_segmentId_fkey" FOREIGN KEY ("segmentId") REFERENCES "conversation_segments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "node_relationships" ADD CONSTRAINT "node_relationships_proposedBy_fkey" FOREIGN KEY ("proposedBy") REFERENCES "proposals"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "node_relationships" ADD CONSTRAINT "node_relationships_sourceNodeId_fkey" FOREIGN KEY ("sourceNodeId") REFERENCES "wiki_nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "node_relationships" ADD CONSTRAINT "node_relationships_targetNodeId_fkey" FOREIGN KEY ("targetNodeId") REFERENCES "wiki_nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "node_relationships" ADD CONSTRAINT "node_relationships_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "record_to_node" ADD CONSTRAINT "record_to_node_nodeId_fkey" FOREIGN KEY ("nodeId") REFERENCES "wiki_nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "record_to_node" ADD CONSTRAINT "record_to_node_nodeVersionId_fkey" FOREIGN KEY ("nodeVersionId") REFERENCES "node_versions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "record_to_node" ADD CONSTRAINT "record_to_node_recordId_fkey" FOREIGN KEY ("recordId") REFERENCES "records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interest_trackings" ADD CONSTRAINT "interest_trackings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interest_mentions" ADD CONSTRAINT "interest_mentions_chatId_fkey" FOREIGN KEY ("chatId") REFERENCES "chats"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interest_mentions" ADD CONSTRAINT "interest_mentions_interestTrackingId_fkey" FOREIGN KEY ("interestTrackingId") REFERENCES "interest_trackings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interest_mentions" ADD CONSTRAINT "interest_mentions_recordId_fkey" FOREIGN KEY ("recordId") REFERENCES "records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "interest_mentions" ADD CONSTRAINT "interest_mentions_segmentId_fkey" FOREIGN KEY ("segmentId") REFERENCES "conversation_segments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_memory_slots" ADD CONSTRAINT "user_memory_slots_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
